[keys]

[custom_commands]
"delta" = { args = ["util", "exec", "--", "bash", "-c", """
jj show -r $change_id --summary --git | delta
"""], show = "diff", key_sequence = ["\\", "d"] }
"resolve" = { key_sequence = [
    "\\",
    "r",
], args = [
    "resolve",
    "-r",
    "$change_id",
    "$file",
] }
"resolve-Revset" = { key_sequence = [
    "\\",
    "R",
], args = [
    "resolve",
    "-r",
    "$change_id",
] }
"new-before" = { key_sequence = [
    "\\",
    "N",
], args = [
    "new",
    "-B",
    "$change_id",
] }
"new-after" = { key_sequence = ["\\", "n"], args = ["new", "-A", "$change_id"] }

[suggest]
[suggest.exec]
mode = "fuzzy" # Accepted values: "off" (default), "regex", "fuzzy".

[colors]
"selected" = { bg = "#2c313a" } # The highlight bar
"border" = "grey"               # The panel splitters
"command_bar" = "white"         # The typing area
